# Ruler Configuration File
# See https://ai.intellectronica.net/ruler for documentation.

# To specify which agents are active by default when --agents is not used,
# uncomment and populate the following line. If omitted, all agents are active.
default_agents = ["cursor", "claude", "codex"]

# Enable nested rule loading from nested .ruler directories
# When enabled, ruler will search for and process .ruler directories throughout the project hierarchy
# nested = false

# --- Agent Specific Configurations ---

[agents.claude]
enabled = true
output_path = "CLAUDE.md"

# OpenAI Codex CLI agent and MCP config
[agents.codex]
enabled = true
output_path = "AGENTS.md"
output_path_config = ".codex/config.toml"

#[agents.gemini-cli]
#enabled = true

# --- Global MCP Server Configuration ---
#[mcp]
# Enable/disable MCP propagation globally (default: true)
#enabled = true
# Global merge strategy: 'merge' or 'overwrite' (default: 'merge')
#merge_strategy = "merge"


# --- MCP Servers ---
#[mcp_servers.filesystem]
#command = "npx"
#args = ["-y", "@modelcontextprotocol/server-filesystem", "/path/to/project"]

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]
env = []

[mcp_servers.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest"]

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"


# --- Global .gitignore Configuration ---
[gitignore]
# Enable/disable automatic .gitignore updates (default: true)
enabled = true